# Build the Python image
FROM python:3.13

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to the Docker image
COPY requirements.txt .

# Create a virtual environment and activate it
RUN python3 -m venv ./venv/vsem
RUN /bin/bash -c "source ./venv/vsem/bin/activate"

# Install the requirements using pip
RUN pip install -r requirements.txt

#Copy data/cspec directory
COPY ./data/cspec .

# Copy the backend directory
COPY ./backend .





