<!-- ===================================================
     View: HomeView.vue
     Description: This view serves as the main page for the Flare application. It includes:
                  - A Banner section with the application title and description.
                  - A Sliding Menu component for navigation between sections.
                  - A Section Divider for visual separation.
                  - An About Section detailing the purpose and goals of Flare.
                  - A Team Section introducing the team members with their roles.
     Author: Anointiyae Beasley
     Date: 11/04/2024
======================================================= -->
<script setup>
  import SlidingMenu from '@/components/SlidingMenu.vue';
  import { useMenuStore } from '@/stores/menuStore'; 

  const menuStore = useMenuStore(); // Instance of useMenuStore
</script>

<template>
    <div class="page-container">
        <!-- Banner Section -->
        <section class="home-banner">
          <!-- Overlay image on the left -->
          <div class="statistics-overlay">
            <img src="@/assets/images/StatisticsOverlay.png" alt="Statistics Overlay" class="overlay-image">
          </div>

          <!-- Text content on the right of the overlay image -->
          <div class="banner-content">
            <h1 class="header-title">Flare</h1>
            <h2 class="subtitle">Showcasing the visualization of AI models operationalized by Semaphore</h2>
          </div>
        </section>


        <section class="sliding-menu-section">
          <SlidingMenu :options="menuStore.slidingMenuOptions" />
          <!-- Popup Message -->
          <div class="popup-message" v-if="true"> 
            <p>More models will be added soon!</p>
          </div>
        </section>

      <!-- Section Divider -->
      <div class="section-divider"> </div>

      <!-- About Section -->
      <section class="about-flare-section" :key="'about-flare-section'">
        <div class="about-flare-container">
          <h2>About Flare</h2>
          <p>
            <strong>Flare</strong> is a student-developed web application designed to deliver valuable knowledge through visualized data from Artificial Intelligence (AI) models. Flare displays predictions generated by AI models created by student researchers at the <strong>Conrad Blucher Institute</strong> and operationalized by <a href="https://github.com/conrad-blucher-institute/semaphore" target="_blank">Semaphore</a>.
          </p>
          <p>
            Through extensive research, development, and collaborative efforts, Flare equips stakeholders—including scientists, policymakers, community leaders, and residents—with data-driven insights to improve decision-making and planning.
          </p>
          <p>
            By providing information on future environmental conditions, Flare aims to help communities in coastal regions prepare for and respond to challenges, such as rising flood levels, changing air temperatures, and fluctuating coastal conditions.
          </p>
        </div>
      </section>

      <!-- Meet the Team Section -->
      <section class="flare-team-section">
        <h2 class="flare-team-header">Meet the Team Behind Flare and Semaphore</h2>
        <div class="flare-team-members">
          <!-- Team Member: Matthew Kastl -->
          <a href="https://www.linkedin.com/in/matthew-kastl-9b8522231/" target="_blank" class="team-member">
            <img src="@/assets/images/MatthewKastl.png" alt="Matthew Kastl" class="team-image">
            <h3 class="flare-team-name">Matthew Kastl</h3>
            <p class="flare-team-role">Graduate Student</p>
          </a>

          <!-- Team Member: Beto Estrada -->
          <a href="https://www.linkedin.com/in/beto-estrada-jr/" target="_blank" class="team-member">
            <img src="@/assets/images/BetoEstrada.png" alt="Beto Estrada" class="team-image">
            <h3 class="flare-team-name">Beto Estrada</h3>
            <p class="flare-team-role">Graduate Student</p>
          </a>

          <!-- Team Member: Anointiyae Beasley -->
          <a href="https://www.linkedin.com/in/anointiyae-beasley-354823230/" target="_blank" class="team-member">
            <img src="@/assets/images/AnointiyaeBeasley.png" alt="Anointiyae Beasley" class="team-image">
            <h3 class="flare-team-name">Anointiyae Beasley</h3>
            <p class="flare-team-role">Undergraduate Student</p>
          </a>

          <!-- Team Member: Savannah Stephenson -->
          <a href="https://www.linkedin.com/in/savannah-stephenson-995516220/" target="_blank" class="team-member">
            <img src="@/assets/images/SavannahStephenson.png" alt="Savannah Stephenson" class="team-image">
            <h3 class="flare-team-name">Savannah Stephenson</h3>
            <p class="flare-team-role">Undergraduate Student</p>
          </a>
          <!-- Team Member: Jeremiah Sosa -->
          <a href="https://www.linkedin.com/in/jeremiah-sosa/" target="_blank" class="team-member">
            <img src="@/assets/images/JeremiahSosa.jpg" alt="Jeremiah Sosa" class="team-image">
            <h3 class="flare-team-name">Jeremiah Sosa</h3>
            <p class="flare-team-role">Undergraduate Student</p>
          </a>
        </div>
      </section>

      <footer class="footer">
        <div class="footer-container">
          <!-- Logo Block -->
          <div class="logo-block">
            <img class="semaphore-logo" src="@/assets/images/Semaphore-Logo.png" alt="Semaphore Logo">
            <img class="cbi-logo" src="@/assets/images/CBI-Logo.png" alt="Conrad Blutcher Institute Logo">
          </div>

          <!-- Links or Credits Block -->
          <div class="footer-info">
            <p>&copy; 2024 Flare. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
</template>

<style>

.page-container {
    padding: 0;
    margin: 0; 
    overflow: hidden; 
}
 /* Banner Section Styling */
.home-banner {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  width: 100%;
  height: 400px; 
  background: var(--banner-gradient-background); 
  overflow: hidden;
}

.statistics-overlay {
  position: absolute;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
  z-index: 1;
  width: 100%; 
}

.overlay-image {
  width: 100%;
  height: auto;
  opacity: 20%; 
}


.banner-content {
  flex: 1; 
  display: flex; 
  flex-direction: column; 
  justify-content: flex-end; /* Push content to the bottom */
  align-items: center; 
  text-align: center; 
  padding-bottom: 100px; 
  height: 100%; 
}

.header-title {
  font-size: 7rem; /* Adjust font size for the title */
  z-index: 2;
  line-height: 1.4; /* Line height for readability */
  margin: 0; /* Remove any default margin */
  color: var(--primary-background)
}

.subtitle {
  font-size: rem; 
  z-index: 1;
  font-weight: 400;
  color: var(--primary-background);
  margin: 0;
}

/* Slidig Menu Section Styles*/
.sliding-menu-section{
  height: 500px;
  align-items: center;
}

/* Popup Message Styling */
.popup-message {
  position: absolute;
  top: 420px; /* Distance from the top of the section */
  right: 20px; 
  background-color: var(--primary-text-light-background); 
  color: var(--primary-background);
  padding: 10px 20px; /* Padding around the text */
  border-radius: 8px; /* Rounded corners */
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); 
  font-size: 1rem; 
  font-weight: bold;
  animation: fadeInSlideDown 0.5s ease-out, vibrate 0.6s ease-in 0.5s; /* Referencing animations that are listed in main.css */
}

.popup-message p {
  margin: 0; /* Remove default margin */
}



/* About Section Styles */
.about-flare-section {
  display: flex;
  justify-content: center;
  align-items: center;
  height: auto;
  overflow: hidden;


  
}

.about-flare-container {
  max-width:  1100px; 
  height: 100%;
  min-height: 500px; 
  width: 100%;
  text-align: center;
  padding: 30px;
  margin: 0 auto; /* Center content */
  box-sizing: border-box; /* Include padding in the dimensions */
}


.about-flare-section h2 {
  font-size: 2.6rem;
  color: var(--primary-text-light-background);
  margin-bottom: 20px;
  font-weight: bold;
  margin: 0 auto;
 
}

.about-flare-section p {
  font-size: 1.6rem;
  line-height: 2; 
  color:var(--secondary-text);
  margin-bottom: 15px;
  margin: 0 auto;
  
}

.about-flare-section strong {
  color: var(--primary-text-light-background);
}

.about-flare-section a {
  color: #007bff;
  text-decoration: none;
  font-weight: bold;
}

.about-flare-section a:hover {
  color: var(--primary-text-light-background);
  text-decoration: underline; /* Add underline on hover for links */
}

/* Team Section Styles*/
.flare-team-section {
  background: var(--section-gradient-background);
  color: var(--primary-background); 
  text-align: center;
  max-width: 100%;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); 
  padding: 40px 20px; 
  height: auto;
  overflow: hidden; 
}

.flare-team-header {
  font-size: 2.6rem;
  color:var(--primary-text-dark-background);;
  margin-bottom: 30px;
  padding: 50px;
}

.flare-team-members {
  display: flex;
  flex-wrap: wrap; 
  justify-content: center;
  gap: 70px; 
  padding-bottom: 50px;

}

.team-member {
  background-color: var(--primary-background);
  border-radius: 8px; /* Rounded corners for the card */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
  text-align: center;
  padding: 40px;
  width: 250px; 
  transition: transform 0.3s ease, box-shadow 0.3s ease; /* Hover effect */
  text-decoration: none;
}

.team-member:hover {
  transform: translateY(-5px); /* Slight lift on hover */
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Stronger shadow on hover */
}

.team-image {
  width: 80%;
  height: 80%;
  object-fit: cover; /* Crop the image to fit the container */
  border-radius: 8px; /* Rounded corners */
  margin-bottom: 15px;
}

.flare-team-name {
  font-size: 1.25rem;
  color: var(--primary-text-light-background);
  margin-bottom: 10px;
}

.flare-team-role {
  font-size: 1rem;
  color:var(--secondary-text);
}

/* General Footer Styles */
.footer {
  background: var(--navy-blue); 
  padding: 20px;
  text-align: center;
  color: var(--primary-text-dark-background);
}

.footer-container {
  flex-direction: column; /* Stack elements vertically*/
  align-items: center;
  gap: 15px; /* Add space between elements */
}

/* Logo Block */
.logo-block {
  justify-content: center;
  gap: 40px; 
}

.semaphore-logo {
    width: 100px; 
    height: 100px;
  }
  .cbi-logo{
    width: 400px; 
    height: 100px;
  }


/* Footer Info Block */
.footer-info {
  font-size: 0.9rem; /* Adjust font size for smaller screens */
  text-align: center; /* Center the text */
  line-height: 1.4;
}

@media (max-width: 930px) {
  .home-banner {
    flex-direction: column;
    height: 250px;

  }

  .page-container {
    overflow-x: hidden; 
    width: 100%; 
    position: relative; 
  }
  .overlay-image {
    width: 100%;
    height: 300px;
    opacity: 20%; 
  }

  .banner-content {
    padding-bottom: 40px;
  }

  .header-title {
    font-size: 2.3rem; /* Reduced size for mobile */
    line-height: 1.3;
  }

  .subtitle {
    font-size: .9rem; /* Smaller subtitle for readability */
  }

  .sliding-menu-section {
    height: auto;
    padding: 20px 10px;
  }

  .popup-message {
    font-size: 0.7rem; /* Smaller size for popup text */
    padding: 5px 5px;
    position: absolute;
    right: 0;
    top: 255px; /* Ensure it starts just below the button */
    overflow: hidden;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    z-index: 20;
    min-width: 200px;
    animation: none;
    
  }

  .about-flare-section {
    display:flex;
    flex-direction: column;
   
  }

  .about-flare-container {
    max-width: 100%;
    padding: 10px;
  }

  .about-flare-section h2 {
    font-size: 1.6rem; 
    padding-top: 20px;
  }

  .about-flare-section p {
    font-size: 1rem; 
    line-height: 1.5; 
    padding-right: 20px;
    padding-left: 20px;
  }

  .flare-team-section {
    padding: 5px 90px;
  }

  .flare-team-header {
    font-size: 1.3rem; 
    padding: 20px;
  }

  .flare-team-members {
    gap: 30px;
  }

  .team-member {
    width: 200px;
  }

  .team-image {
    width: 200px;
    height: 200px;
  }

  .flare-team-name {
    font-size: 1rem; 
  
  }

  .flare-team-role {
    font-size: 0.85rem;

  }

  .footer {
    padding: 15px; 
  }

  .semaphore-logo {
    width: 85px; 
    height: 85px;
  }
  .cbi-logo{
    width: 350px; 
    height: 80px;
  }


  .footer-info {
    font-size: 0.8rem; 
  }
 
}


</style>
