<!-- ===================================================
     View: HomeView.vue
     Description: This view serves as the main page for the Flare application. It includes:
                  - A Banner section with the application title and description.
                  - A Sliding Menu component for navigation between sections.
                  - A Section Divider for visual separation.
                  - An About Section detailing the purpose and goals of Flare.
                  - A Team Section introducing the team members with their roles.
     Author: Anointiyae Beasley
     Date: 11/04/2024
======================================================= -->
<script setup>import SlidingMenu from '@/components/SlidingMenu.vue';</script>

<template>
    <div class="page-container">
        <!-- Banner Section -->
        <section class="banner">
            <div class="banner-overlay">
                <!-- <img src="/OIP.jpg" alt="Background Image 1" class="overlay-image"> -->
            </div>
            <div class="banner-content">
                <h1 class="header-title">Flare</h1>
                <p class="header-subtext">Delivering valuable insights through AI model predictions.</p>
            </div>
        </section>

        <!-- Sliding Menu Section -->
        <section class="sliding-menu-section">
            <SlidingMenu :options="slidingMenuOptions" />
        </section>

        <!-- Section Divider -->
        <div class="section-divider"> </div>

        <!-- About Section -->
        <section class="about-section">
            <h2>About Flare</h2>
            <p>
                <strong>Flare</strong> is a student-developed web application designed to deliver valuable knowledge through visualized data from Artificial Intelligence(AI) models. Flare displays predictions generated by AI models created by student researchers at the <strong>Conrad Blucher Institute</strong> and operationalized by <a href="https://github.com/conrad-blucher-institute/semaphore" target="_blank">Semaphore</a>.  
                Through extensive research, development, and collaborative efforts, Flare equips stakeholders—including scientists, policymakers, community leaders, and residents—with data-driven insights to improve decision-making and planning.
                By providing information on future environmental conditions, Flare aims to help communities in coastal regions prepare for and respond to challenges, such as rising flood levels, changing air temperatures, and fluctuating coastal conditions.
            </p>
        </section>

        <!-- Meet the Team Section -->
        <section class="team-section">
            <h2>Meet the Team</h2>
            <div class="team-members">
                <div class="matthew">
                    <img src="@/assets/images/MatthewKastl.png" alt="Matthew Kastl">
                    <h1> Matthew Kastl</h1>
                    <p>Graduate Student</p>
                </div>

                <div class="beto">
                    <img src="@/assets/images//BetoEstrada.png" alt="Beto Estrada">
                    <h1> Beto Estrada</h1>
                    <p>Graduate Student</p>
                </div>

                <div class="anointiyae">
                    <img src="@/assets/images//AnointiyaeBeasley.png" alt="Anointiyae Beasley">
                    <h1> Anointiyae Beasley</h1>
                    <p>Undergraduate Student</p>
                </div>

                <div class="savannah">
                <img src="@/assets/images//SavannahStephenson.png" alt="Savannah Stephenson">
                <h1> Savannah Stephenson</h1>
                <p>Graduate Student</p>
                </div>
            </div>
        </section>
    </div>
</template>

<style scoped>

.banner {
  position: relative;
  width: 100%; 
  background: linear-gradient(to bottom, #000000,#004184, #05c1d4); 
  color: #fff; /* Text color for contrast */
  padding: 100px 0px;
  text-align: center;
  overflow: hidden; 
  margin: 0; /* Remove any default margin */
}

.section-divider {
    background-color: #2c849b;
    padding: 20px 0px;
    width: 100%;; /* Full viewport width */
}
.team-section {
    background-color: #0f4f66;
    color: white;
    left: 0;

}
.page-container {
    width: 100%;; /* Full viewport width */

    padding: 0;
    margin: 0; /* Remove any default margin */
    overflow: hidden; 
}
.about-section{
    padding: 100px 0px;
}

.banner-content {
  position: relative;
  max-width: 1000px;
  margin: auto;
}

.header-title {
    font-size: 80px;
}
.header-subtext{
    font-size: 20px; 
    margin: auto;
}

</style>
