<!-- ===================================================
     View: HomeView.vue
     Description: This view serves as the main page for the Flare application. It includes:
                  - A Banner section with the application title and description.
                  - A Sliding Menu component for navigation between sections.
                  - A Section Divider for visual separation.
                  - An About Section detailing the purpose and goals of Flare.
                  - A Team Section introducing the team members with their roles.
     Author: Anointiyae Beasley
     Date: 11/04/2024
======================================================= -->
<script setup>
  import SlidingMenu from '@/components/SlidingMenu.vue';
  import { useMenuStore } from '@/stores/menuStore'; 

  const menuStore = useMenuStore(); // Instance of useMenuStore
</script>

<template>
  <div class="overflow-hidden">
    <!-- Banner Section -->
    <section class="relative flex items-center justify-center h-[300px] lg:h-[400px] bg-banner-gradient">
      <!-- Overlay Image -->
      <div class="absolute inset-y-0 left-0 w-full opacity-20">
        <img src="@/assets/images/StatisticsOverlay.png" alt="Statistics Overlay" class="w-full h-full object-cover">
      </div>
      <!-- Text Content -->
      <div class="relative text-center">
        <h1 class="text-5xl lg:text-7xl font-bold text-white leading-tight lg:text-8xl">Flare</h1>
        <h2 class="mt-4 text-lg lg:text-xl font-medium text-gray-200 lg:text-2xl">Showcasing the visualization of AI models operationalized by Semaphore</h2>
      </div>
    </section>

    <!-- Sliding Menu Section -->
    <section class="flex items-center justify-center lg:min-h-[500px] lg:max-h-[700px]">
      <SlidingMenu :options="menuStore.slidingMenuOptions" />
    </section>

    <!-- Section Divider -->
    <div class="h-[40px] bg-section-gradient"></div>

    <!-- About Section -->
    <section class="py-10 px-6 md:px-20 bg-gray-100">
      <div class="max-w-4xl mx-auto text-center">
        <h2 class=" text-2xl lg:text-3xl font-bold text-dark-text mb-6">About Flare</h2>
        <p class="text-lg text-gray-700 mb-4">
          <strong class="font-semibold text-dark-text">Flare</strong> is a student-developed web application designed to deliver valuable knowledge through visualized data from Artificial Intelligence (AI) models. Flare displays predictions generated by AI models created by student researchers at the <strong class="font-semibold text-dark-text">Conrad Blucher Institute</strong> and operationalized by <a href="https://github.com/conrad-blucher-institute/semaphore" target="_blank" class="text-blue-500 hover:underline">Semaphore</a>.
        </p>
        <p class="text-lg text-gray-700 mb-4">
          Through extensive research, development, and collaborative efforts, Flare equips stakeholders—including scientists, policymakers, community leaders, and residents—with data-driven insights to improve decision-making and planning.
        </p>
        <p class="text-lg text-gray-700">
          By providing information on future environmental conditions, Flare aims to help communities in coastal regions prepare for and respond to challenges, such as rising flood levels, changing air temperatures, and fluctuating coastal conditions.
        </p>
      </div>
    </section>

    <!-- Meet the Team Section -->
    <section class="py-10 bg-section-gradient">
      <h2 class="text-xl lg:text-3xl font-bold text-center text-white mb-10">Meet the Team Behind Flare and Semaphore</h2>
      <div class="flex flex-wrap justify-center gap-10">
        <!-- Team Member -->
        <a href="https://www.linkedin.com/in/matthew-kastl-9b8522231/" target="_blank" class="flex flex-col items-center w-[220px]  lg:w-[300px] lg:h-[400px] bg-gray-100 p-6 rounded-lg shadow-lg hover:shadow-xl transition">
          <img src="@/assets/images/MatthewKastl.png" alt="Matthew Kastl" class="w-40 h-40 lg:w-60 lg:h-60 rounded-full mb-4 object-cover">
          <h3 class="text-sm lg:text-2xl font-semibold text-gray-800">Matthew Kastl</h3>
          <p class="text-sm lg:text-lg text-gray-600">Graduate Student</p>
        </a>

        <!-- Repeat for other team members -->
        <a href="https://www.linkedin.com/in/beto-estrada-jr/" target="_blank" class="flex flex-col items-center w-[220px]  lg:w-[300px] lg:h-[400px] bg-gray-100 p-6 rounded-lg shadow-lg hover:shadow-xl transition">
          <img src="@/assets/images/BetoEstrada.png" alt="Beto Estrada" class="w-40 h-40 lg:w-60 lg:h-60 rounded-full mb-4 object-cover">
          <h3 class="text-sm lg:text-2xl font-semibold text-gray-800">Beto Estrada</h3>
          <p class="text-sm lg:text-lg text-gray-600">Graduate Student</p>
        </a>

        <a href="https://www.linkedin.com/in/anointiyae-beasley-354823230/" target="_blank" class="flex flex-col items-center w-[220px]  lg:w-[300px] lg:h-[400px] bg-gray-100 p-6 rounded-lg shadow-lg hover:shadow-xl transition">
          <img src="@/assets/images/AnointiyaeBeasley.png" alt="Anointiyae Beasley" class="w-40 h-40 lg:w-60 lg:h-60  rounded-full mb-4 object-cover">
          <h3 class="text-sm lg:text-2xl font-semibold text-gray-800">Anointiyae Beasley</h3>
          <p class="text-sm lg:text-lg text-gray-600">Undergraduate Student</p>
        </a>

        <a href="https://www.linkedin.com/in/savannah-stephenson-995516220/" target="_blank" class="flex flex-col items-center w-[220px] lg:w-[300px] lg:h-[400px] bg-gray-100 p-6 rounded-lg shadow-lg hover:shadow-xl transition">
          <img src="@/assets/images/SavannahStephenson.png" alt="Savannah Stephenson" class="w-40 h-40 lg:w-60 lg:h-60  rounded-full mb-4 object-cover">
          <h3 class="text-sm lg:text-[22px] font-semibold text-gray-800">Savannah Stephenson</h3>
          <p class="text-sm lg:text-lg text-gray-600">Undergraduate Student</p>
        </a>

        <a href="https://www.linkedin.com/in/jeremiah-sosa/" target="_blank" class="flex flex-col items-center w-[220px]  lg:w-[300px] lg:h-[400px] bg-gray-100 p-6 rounded-lg shadow-lg hover:shadow-xl transition">
          <img src="@/assets/images/JeremiahSosa.jpg" alt="Jeremiah Sosa" class="w-40 h-40 lg:w-60 lg:h-60  rounded-full mb-4 object-cover">
          <h3 class="text-sm lg:text-2xl font-semibold text-gray-800">Jeremiah Sosa</h3>
          <p class="text-sm lg:text-lg text-gray-600">Undergraduate Student</p>
        </a>
      </div>
    </section>

    <!-- Footer -->
    <footer class="bg-navy-blue py-6 text-center">
      <div class="flex justify-center gap-2 lg:gap-10">
        <img src="@/assets/images/Semaphore-Logo.png" alt="Semaphore Logo" class="w-[100px] lg:w-[200px] lg:h-[200px]">
        <img src="@/assets/images/CBI-Logo.png" alt="Conrad Blutcher Institute Logo" class="w-[230px] h-[75px] pt-5 lg:pt-10 lg:w-[550px] lg:h-[150px]">
      </div>
      <p class="mt-4 text-sm text-gray-300">&copy; 2024 Flare. All rights reserved.</p>
    </footer>
  </div>
</template>
